# Generated by Django 3.2 on 2024-01-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products_of_the_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='no', max_length=100)),
                ('product_code', models.CharField(default='no', max_length=100)),
                ('price', models.FloatField(default=0)),
            ],
        ),
    ]
