# Generated by Django 3.2 on 2024-01-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_products_of_the_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products_of_the_company',
            name='id',
        ),
        migrations.AlterField(
            model_name='products_of_the_company',
            name='product_code',
            field=models.CharField(default='no', max_length=100, primary_key=True, serialize=False),
        ),
    ]
